from datetime import datetime
from pathlib import Path
from .config import WikiConfig
from .state import StateDB
from .storage import sanitize_filename, parse_note, write_note

def generate_index(config: WikiConfig, db: StateDB) -> Path:
    """Write wiki/index.md — a flat catalogue of concepts and sources."""
    now = datetime.now().strftime("%Y-%m-%d")
    
    articles = db.list_articles(drafts_only=False)
    published = [a for a in articles if not a.is_draft]
    
    concept_entries = []
    source_entries = []
    connection_entries = []
    
    for art in published:
        stem = Path(art.path).stem
        if "/sources/" in art.path or "\\sources\\" in art.path:
            source_entries.append((art.title, "", stem))
        elif "/connections/" in art.path or "\\connections\\" in art.path:
            connection_entries.append((art.title, "Connection", stem))
        else:
            concept_entries.append((art.title, "", stem))
            
    # Also pick up source summary pages directly from wiki/sources/
    if config.sources_dir.exists():
        for md in sorted(config.sources_dir.glob("*.md")):
            try:
                meta, _ = parse_note(md)
                title = meta.get("title", md.stem)
                if not any(e[0] == title for e in source_entries):
                    quality = meta.get("quality", "")
                    src_file = meta.get("source_file", "")
                    hint = quality if quality else src_file
                    source_entries.append((title, hint, md.stem))
            except Exception:
                pass
                
    qa_entries = []
    if config.qa_dir.exists():
        for md in sorted(config.qa_dir.glob("*.md")):
            try:
                meta, _ = parse_note(md)
                title = meta.get("title", md.stem)
                qa_entries.append((title, "Q&A Answer", md.stem))
            except Exception:
                pass

    daily_entries = []
    if config.daily_dir.exists():
        for md in sorted(config.daily_dir.glob("*.md")):
            daily_entries.append((md.stem, "Daily Log/Memory", md.stem))
            
    concept_entries.sort(key=lambda x: x[0].lower())
    source_entries.sort(key=lambda x: x[0].lower())
    qa_entries.sort(key=lambda x: x[0].lower())
    connection_entries.sort(key=lambda x: x[0].lower())
    daily_entries.sort(key=lambda x: x[0].lower(), reverse=True) # newest first
    
    body_lines = ["# Wiki Index", ""]
    
    if daily_entries:
        body_lines.append("## Daily Logs")
        for title, hint, stem in daily_entries:
            link = f"[[{stem}|{title}]]" if stem != title else f"[[{title}]]"
            entry = f"- {link} — {hint}"
            body_lines.append(entry)
        body_lines.append("")
    
    if concept_entries:
        body_lines.append("## Concepts")
        for title, hint, stem in concept_entries:
            link = f"[[{stem}|{title}]]" if stem != title else f"[[{title}]]"
            entry = f"- {link}"
            if hint:
                entry += f" — {hint}"
            body_lines.append(entry)
        body_lines.append("")
        
    if connection_entries:
        body_lines.append("## Connections")
        for title, hint, stem in connection_entries:
            link = f"[[{stem}|{title}]]" if stem != title else f"[[{title}]]"
            entry = f"- {link}"
            if hint:
                entry += f" — {hint}"
            body_lines.append(entry)
        body_lines.append("")
        
    if source_entries:
        body_lines.append("## Sources")
        for title, hint, stem in source_entries:
            link = f"[[{stem}|{title}]]" if stem != title else f"[[{title}]]"
            entry = f"- {link}"
            if hint:
                entry += f" — {hint}"
            body_lines.append(entry)
        body_lines.append("")
        
    if qa_entries:
        body_lines.append("## Q&A")
        for title, hint, stem in qa_entries:
            link = f"[[{stem}|{title}]]" if stem != title else f"[[{title}]]"
            entry = f"- {link}"
            if hint:
                entry += f" — {hint}"
            body_lines.append(entry)
        body_lines.append("")
        
    total = len(concept_entries) + len(source_entries) + len(qa_entries) + len(connection_entries)
    body_lines.append(f"_Auto-generated by olw. {total} entries._")
    
    meta = {"title": "Wiki Index", "tags": ["meta", "index"], "updated": now}
    write_note(config.index_file, meta, "\n".join(body_lines))
    return config.index_file

def append_log(config: WikiConfig, entry: str) -> Path:
    """Append a timestamped entry to wiki/log.md."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    if not config.log_file.exists():
        config.log_file.parent.mkdir(parents=True, exist_ok=True)
        write_note(config.log_file, {"title": "Operation Log", "tags": ["meta"]}, "# Operation Log\n")
        
    with open(config.log_file, "a", encoding="utf-8") as f:
        f.write(f"\n## [{now}] {entry}\n")
        
    return config.log_file
